# Site settings
title: DevOps tools.
description: > # this means to ignore newlines until "baseurl:"
  A curated list of DevOps tools, technologies, platforms and resources.
  Things to help/grow you in DevOps or SRE area.
url: "https://juanmancebo.github.io"
github_username:  juanmancebo

plugins:
  - jekyll-relative-links
  - jemoji  
relative_links:
  enabled: true
  collections: true
author: "Juan C. Mancebo"
